import type { NextPage } from "next";

import Head from "next/head";
import NavBar from "../components/NavBar/NavBar";
import Resume from "../components/Resume/Resume";
import Paper from "@mui/material/Paper";

import styles from "../styles/Home.module.scss";

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <NavBar />
      </nav>

      <main className={styles.Main}>
        <Paper className={styles.Paper}>
          <Resume />
        </Paper>
      </main>
    </div>
  );
}

export default Home as NextPage;
